version: "3.7"

services:

  backend:
    build: .
    volumes:
      - .:/home/nipss
      - static_volume:/home/nipss/static
      - media_volume:/home/nipss/media
    ports:
      - '8000:8000'
    env_file:
      - .env

    depends_on:
      - redis

    restart: on-failure
    
  redis:
    image: redis:alpine

    restart: on-failure
    
volumes:
  static_volume:
  media_volume:
  