version: "3.7"

services:

  backend:
    build: .
    volumes:
      - .:/home/nipss
      - static_volume:/home/nipss/static
      - media_volume:/home/nipss/media
    ports:
      - '8000:8000'
    env_file:
      - .env

    restart: on-failure
    
  nginx:
    restart: always
    build: ./nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/nipss/static
      - media_volume:/home/nipss/media  
      
volumes:
  static_volume:
  media_volume:
  