# Generated by Django 4.2.9 on 2024-02-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patientprincipal_spouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprincipal',
            name='file_number',
            field=models.CharField(max_length=10),
        ),
    ]
