# Generated by Django 4.2.9 on 2024-02-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_patientprincipal_spouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='file_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='children',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='patientprincipal',
            name='file_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='file_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
