# Generated by Django 4.2.9 on 2024-02-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_children_file_number_alter_children_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='file_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='file_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
