# Generated by Django 4.2.9 on 2024-02-23 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_patientprincipal_file_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpouseContinuationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spouse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_spouse_continuation_sheet', to='core.spouse')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalContinuationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_principal_principal_continuation_sheet', to='core.patientprincipal')),
            ],
        ),
        migrations.CreateModel(
            name='ChildContinuationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_child_continuation_sheet', to='core.children')),
            ],
        ),
    ]
