# Generated by Django 4.2.9 on 2024-02-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_spousecontinuationsheet_principalcontinuationsheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpouseTestRequestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('doctor_request_description', models.TextField()),
                ('test_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_spouse_test_request_sheet', to='core.spouse')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalPatientTestRequestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('doctor_request_description', models.TextField()),
                ('test_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_patient_principal_patient_test_request_sheet', to='core.patientprincipal')),
            ],
        ),
        migrations.CreateModel(
            name='ChildTestRequestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('doctor_request_description', models.TextField()),
                ('test_result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_child_test_request_sheet', to='core.children')),
            ],
        ),
    ]
