# Generated by Django 4.2.9 on 2024-03-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_spousetestrequestsheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpousePrescriptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('doctor_prescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_spouse_prescription', to='core.spouse')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalPatientPrescriptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('doctor_prescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_patient_principal_patient_prescription', to='core.patientprincipal')),
            ],
        ),
        migrations.CreateModel(
            name='ChildPrescriptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False)),
                ('doctor_prescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_child_prescription', to='core.children')),
            ],
        ),
    ]
