# Generated by Django 4.2.9 on 2024-03-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_spouseprescriptionform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprescriptionform',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childtestrequestsheet',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principalpatientprescriptionform',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principalpatienttestrequestsheet',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spouseprescriptionform',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spousetestrequestsheet',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
