# Generated by Django 4.2.9 on 2024-03-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_admission_options_alter_bed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprescriptionform',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principalpatientprescriptionform',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spouseprescriptionform',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
