# Generated by Django 4.2.9 on 2024-04-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_childprescriptionform_is_billed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprincipal',
            name='nhis_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientprincipal',
            name='patient_type',
            field=models.CharField(choices=[('Participant', 'Participant'), ('Enrollee', 'Enrollee'), ('Non NHIS', 'Non NHIS')], max_length=20),
        ),
    ]
