# Generated by Django 4.2.9 on 2024-04-06 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_alter_patientprincipal_nhis_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='is_booked',
            new_name='is_attended',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='status',
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_booking_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_booking_appointment', to='core.patientprincipal'),
        ),
    ]
