# Generated by Django 4.2.9 on 2024-04-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_is_booked_bookappointment_is_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_booking_appointment', to='core.doctor'),
        ),
    ]
