# Generated by Django 4.2.9 on 2024-04-06 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_alter_bookappointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='doctor_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile_booking_appointment', to='core.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='doctor_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user_booking_appointment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
