# Generated by Django 4.2.9 on 2024-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_bookappointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprincipal',
            name='has_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
