# Generated by Django 4.2.9 on 2024-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_device_registered',
            field=models.BooleanField(default=False),
        ),
    ]
